/**
 * 
 */
window.navBar_englishLabelList || (window.navBar_englishLabelList = {});
window.navBar_frenchLabelList || (window.navBar_frenchLabelList = {});
window.welcome_frenchLabelList || (window.welcome_frenchLabelList = {});
window.welcome_englishLabelList || (window.welcome_englishLabelList = {});
window.navBtnSection_frenchLabelList || (window.navBtnSection_frenchLabelList = {});
window.navBtnSection_englishLabelList || (window.navBtnSection_englishLabelList = {});
window.orderDetails_frenchLabelList || (window.orderDetails_frenchLabelList = {});
window.orderDetails_englishLabelList || (window.orderDetails_englishLabelList = {});

navBar_englishLabelList = {
    'HOME': 'HOME',
    'CREATE ORDER': 'CREATE ORDER',
    'LIST ORDER': 'LIST ORDER',
    'ADMIN SETTINGS': 'ADMIN SETTINGS'


};
navBar_frenchLabelList = {
    'HOME': 'ACCUEIL',
    'CREATE ORDER': 'NOUVELLE COMMANDE',
    'LIST ORDER': 'COMMANDE DE LA LISTE',
    'ADMIN SETTINGS': 'REGLAGES ADMIN'
};
welcome_englishLabelList = {
    'Welcome to': 'Welcome to',
    'Create': 'Create',
    'Create new orders and its associate components': 'Create new orders and its associate components',
    'List Orders': 'List Orders',
    'View list of orders': 'View list of orders',
    'Admin settings': 'Admin settings',
    'Configure roles and privileges': 'Configure roles and privileges'
};
welcome_frenchLabelList = {
    'Welcome to': 'Bienvenue \xE0',
    'Create': 'Cr\xE9er',
    'Create new orders and its associate components': 'Cr\xE9er de nouvelles commandes et de ses composants associ\xE9s',
    'List Orders': 'Liste des commandes',
    'View list of orders': 'Voir la liste des commandes',
    'Admin settings': 'Reglages admin',
    'Configure roles and privileges': 'Configurer les r\xF4les et les privileges'
};
navBtnSection_frenchLabelList = {
    'Print': 'Imprimer',
    'Save': 'Enregistrer',
    'Close': 'Fermer',
    'Cancel': 'Annuler',
    'Duplicate': 'Dupliquer',
    'Rewind': 'Rembobiner',
    'Forward to Next Stage': 'Transf\xE9rer \xE0 l\'\xE9tape suivante',
    'Order Id': 'Num\xE9ro de commande',
    'Requester Name': 'Nom emetteur',
    'Current Actor': 'Acteur actuel',
    'Stage': '\xC9tape',
    'Status': 'statut',
    'Total order amount': 'Montant total de la commande'
};
navBtnSection_englishLabelList = {
    'Print': 'Print',
    'Save': 'Save',
    'Close': 'Close',
    'Cancel': 'Cancel',
    'Duplicate': 'Duplicate',
    'Rewind': 'Rewind',
    'Forward to Next Stage': 'Forward to Next Stage',
    'Order Id': 'Order Id',
    'Requester Name': 'Requester Name',
    'Current Actor': 'Current Actor',
    'Stage': 'Stage',
    'Status': 'Status',
    'Total order amount': 'Total order amount'
};
orderDetails_frenchLabelList = {
    'Order Detail': 'D\xE9tails de la commande',
    'Site/Workshop Prototype': 'Site / Atelier Prototype',
    'Geosite': 'Geosite',
    'Prototype Order': 'Prototype Commander',
    'Proto Type': 'Type de Proto',
    'Type of the prototype order': 'Type de la commande prototype',
    'Date of the order': 'Date de la commande',
    'Total order amount': 'Montant total de la commande',
    'Order Status': 'Status de la commande',
    'PCC': 'PCC',
    'Open Order': 'Commande ouverte',
    'Frittage': 'Frittage',
    'E52': 'E52',
    'IntraLE': 'IntraLE',
    'Actor': 'Acteur',
    'Requester': 'Emetteur',
    'MEP Study': 'MEP Etude',
    'Quality': 'Qualit\xE9',
    'Proto workshop': 'Atelier Proto',
    'Control management': 'Controle de Gestion',
    'FO Trade': 'Commerce FO',
    'ADV': 'ADV',
    'Project manager': 'Chef de Projet',
    'Customer Detail': 'D\xE9tail du client',
    'N0 customer order': 'de la commande client',
    'Customer name': 'Nom du client',
    'Customer code': 'Code client',
    'Branch code': 'Code branche',
    'Provider code': 'Code fournisseur',
    'Plateform': 'Plateforme',
    'Incoterms': 'Incoterms',
    'Place': 'Lieu',
    'Customer receiver name': 'Nom du receptionnaire client',
    'Customer receiver telephone': 'T\xE9l\xE9phone du receptionnaire client',
    'Allocation of turnover': 'Affectation du Chiffre d\'Affaire',
    'Final delivery Address': 'Address de livraiso finale',
    'Additional address': 'Compl\xE9ment d\'adresse',
    'Site address': 'Adresse du site',
    'Customer order': 'Commande client',
    'Add Attach':'Ajouter Joindre',
    'Component': 'Composant',
    'Link': 'Link',
    'Customer ref': 'R\xE9f\xE9rence client',
    'Product Designation': 'D\xE9signation du produit',
    'Product Type': 'Type de produit',
    'USP': 'PVU',
    'Total Quantity': 'Quantit\xE9 totale',
    'Total amount': 'Montant total',
    'Component status': 'Statut du composant',
    'Quantity produced': 'Quantit\xE9 fabriqu\xE9',
    'Quantity App. Quality': 'Quantit\xE9 App. Qualit\xE9',
    'Quantity Dfi': 'Quantit\xE9 BLi',
    'Quantity Delivered  to the customer': 'Quantit\xE9 livr\xE9e Au',
    'Invoiced amount': 'Quantit\xE9 factur\xE9e',
    'Draft': 'Brouillon',
    'Next': 'Prochain',
    'Back': 'Arri\xE9re',
    'Show': 'Montrer',
    'Entries': 'Entr\xE9es',
    'Back': 'Arri\xE9re',
    'Create component': 'Creation d\'un Comosant'
};
orderDetails_englishLabelList = {
	'Order Detail': 'Order Detail',
    'Site/Workshop Prototype': 'Site / Workshop Prototype',
    'Geosite': 'Geosite',
    'Prototype Order': 'Prototype Order',
    'Proto Type': 'Proto Type',
    'Type of the prototype order': 'Type of the prototype order',
    'Date of the order': 'Date of the order',
    'Total order amount': 'Total Order Amount',
    'Order Status': 'Order Status',
    'PCC': 'PCC',
    'Open Order': 'Open Order',
    'Frittage': 'Frittage',
    'E52': 'E52',
    'IntraLE': 'IntraLE',
    'Actor':'Actor',
    'Requester': 'Requester',
    'MEP Study': 'MEP Study',
    'Quality': 'Quality',
    'Proto workshop': 'Proto workshop',
    'Control management': 'Control management',
    'FO Trade': 'FO Trade',
    'ADV': 'ADV',
    'Project manager': 'Project manager',
    'Customer Detail': 'Customer Detail',
    'N0 customer order': 'Customer Order',
    'Customer name': 'Customer Name ',
    'Customer code': 'Customer Code',
    'Branch code': 'Branch Code',
    'Provider code': 'Provider Code',
    'Plateform': 'Plateform',
    'Incoterms': 'Incoterms',
    'Place': 'Place',
    'Customer receiver name': 'Customer Receiver Name',
    'Customer receiver telephone': 'Customer Receiver Telephone',
    'Allocation of turnover': 'Allocation of Turnover',
    'Final delivery Address': 'Final Delivery Address',
    'Additional address': 'Additional Address',
    'Site address': 'Site Address',
    'Customer order': 'Customer Order',
    'Add Attach':'Add Attach',
    'Component': 'Component',
    'Link': 'Link',
    'Customer ref': 'Cus ref',
    'Product Designation': 'P Designation',
    'Product Type': 'P Type',
    'USP': 'USP',
    'Total Quantity': 'T Qty',
    'Total amount': 'T amt',
    'Component status': 'Component status',
    'Quantity produced': 'Qty produced',
    'Quantity App. Quality': 'Qty App. Quality',
    'Quantity Dfi': 'Qty Dfi',
    'Quantity Delivered  to the customer': 'Qty Delivered',
    'Invoiced amount': 'Invoiced amt',
    'Draft': 'Draft',
    'Next': 'Next',
    'Show': 'Show',
    'Entries': 'Entries',
    'Back': 'Back',
    'Create component': 'Create component',
    'Back': 'Back',
    'Next': 'Next'
};