window.ApplicationConstants || (window.ApplicationConstants = {});

ApplicationConstants = {

"fetchActorsListByType"			: 	"/fetchController/fetchActorsByType/",
"fetchIncotermsList" 			: 	"/fetchController/fetchIncotermsList",
"fetchCustomersList"			: 	"/fetchController/fetchCustomersList",
"fetchPlateformesList"			: 	"/fetchController/fetchPlateformList",
"fetchPlacesList"				:	"/fetchController/fetchPlacesList",
"fetchSitesList"				:	"/fetchController/fetchSitesList",
"fetchIDList"					:	"/fetchController/fetchIDList",
"fetchComponentIDList"			:	"/fetchController/fetchComponentIDList",
"fetchActorsListBySite"			:	"/fetchController/fetchActorsListBySite/",
"fetchCustomerDetailsbyName"	:	"/fetchController/fetchCustomerDetailsbyName/",
"fetchLaboAddressOnLoad"		:	"/fetchController/fetchLaboAddressOnLoad/",
"fetchUserInfoDetails"			:	"/fetchController/fetchUserDetails/",
"fetchOrderDependencies"		: 	"/fetchController/fetchOrderDependencies",
"fetchComponentdependencies"	:	"/fetchController/fetchComponentdependencies",
"fetchPlanningCustomerDeliveryDetails" : "/fetchController/fetchPlanningCustomerDeliveryDetails/",
"fetchOrdersList"				: 	"/fetchController/fetchOrders",
"fetchProductTypeList"			: 	"/fetchController/fetchProductTypeList",
"fetchPrototypitsList"			: 	"/fetchController/fetchPrototypitsList",
"fetchRandDList"				:	"/fetchController/fetchRandDList",
"fetchTechnologyList"			: 	"/fetchController/fetchTechnologyList",
"fetchClientLaboList"			: 	"/fetchController/fetchClientLaboList",
"fetchAllocationofTurnOverList"	: 	"/fetchController/fetchAllocationofTurnOverList",
"fetchlastPrototypeID"			:	"/fetchController/fetchlastPrototypeID",
"fetchProtypeOrderObject"		:	"/fetchController/fetchProtypeOrderbasedOnID/",
"fetchAttachmentList"			:   "/fetchController/fetchAttachmentList/",
"fetchComponentListforOrder"	:	"/fetchController/fetchComponentListforOrder/",
"fetchQuantityBasedonComponentID":	"/fetchController/fetchQuantityBasedonComponentID/",
"saveOrderUrl"					:	"/order/create",
"updateOrderURL"				:	"/order/updateOrder",
"createcomponent"				:	"/saveComponent/createcomponent",
"saveActorsListURL"				:	"/actorsList/create",
"saveCustomersListURL"			:	"/customerslist/create",
"saveIncotermsListURL"			:	"/incoterm/create",
"savePlacesListURL"				:	"/place/create",
"savePlaterormsListURL"			:	"/plateform/create",
"savesSitesListURL"				:	"/siteslist/create",
"saveProductTypeListURL"		:	"/producttype/create",
"savePrototypistListURL"		:	"/prototypist/create",
"saveTechnologyListURL"			:	"/technology/create",
"saveRandDListURL"				:	"/rAndDController/create",
"saveAllocationListURL"			:	"/allocationController/create",
"saveClientLaboListURL"			:	"/clientLabo/create",
"saveComponentDescription"		:	"/saveComponent/saveComponentDescription",
"savePlanningandCustomerDelivery"	:	"/saveComponent/savePlanningandCustomerDelivery",
"saveTechnicalDefinition"		:	"/clientLabo/create",
"savePlanofLabTests"			:	"/clientLabo/create",
"saveProcessValidation"			:	"/clientLabo/create",
"saveEstimatingCostandDelay"	:	"/clientLabo/create",
"saveForecastPlanning"			:	"/clientLabo/create",
"saveReminder"					:	"/clientLabo/create",
"saveQualitydeliverable"		:	"/clientLabo/create",
"generateNewId"					:	"/idgenerator/createNewID",
"generateNewComponentID"		:	"/compidgenerator/createNewID",
"deleteAttachmentbyID" 			:   "/deleteAttachmentbyID",
"updateAttachmentsURL"			:	"/updateAttachments",
"getuploadUrl"					:	"/getuploadUrl",
"getuploadUrlOnUpdate"			:	"/getuploadUrlOnUpdate",
"updateAttachment"				:	"/updateAttachments",
"createorupdateuser"			:	"/users/createorupdate"
}

