/**
 * 
 */
window.navBar_englishLabelList || (window.navBar_englishLabelList = {});
window.navBar_frenchLabelList || (window.navBar_frenchLabelList = {});
window.welcome_frenchLabelList || (window.welcome_frenchLabelList = {});
window.welcome_englishLabelList || (window.welcome_englishLabelList = {});
window.navBtnSection_frenchLabelList || (window.navBtnSection_frenchLabelList = {});
window.navBtnSection_englishLabelList || (window.navBtnSection_englishLabelList = {});
window.orderDetails_frenchLabelList || (window.orderDetails_frenchLabelList = {});
window.orderDetails_englishLabelList || (window.orderDetails_englishLabelList = {});
window.componentCreation_frenchLabelList || (window.componentCreation_frenchLabelList = {});
window.componentCreation_englishLabelList || (window.componentCreation_englishLabelList = {});
window.adminSetting_frenchLabelList || (window.adminSetting_frenchLabelList = {});
window.adminSetting_englishLabelList || (window.adminSetting_englishLabelList = {});


navBar_englishLabelList = {
    'HOME': 'HOME',
    'CREATE ORDER': 'CREATE ORDER',
    'LIST ORDER': 'LIST ORDER',
    'ADMIN SETTINGS': 'ADMIN SETTINGS',
    'Component List':'COMPONENT LIST'
};
navBar_frenchLabelList = {
    'HOME': 'ACCUEIL',
    'CREATE ORDER': 'NOUVELLE COMMANDE',
    'LIST ORDER': 'COMMANDE DE LA LISTE',
    'ADMIN SETTINGS': 'REGLAGES ADMIN',
    'Component List':'LISTE DES COMPOSANTS'
};
welcome_englishLabelList = {
	'determine' : 'hide',
    'Welcome to': 'Welcome to',
    'Create': 'Create New Order',
    'Create new orders and its associate components': 'Create new orders and its associate components',
    'List Orders': 'List Orders',
    'View list of orders': 'View list of orders',
    'Admin settings': 'Admin settings',
    'Configure roles and privileges': 'Configure roles and privileges',
    'Create new order':'Create new order',
    'Configure workflow':'Configure workflow',
    'List components':'List Components'
};
welcome_frenchLabelList = {
    'Welcome to': 'Bienvenue \xE0',
    'Create': 'Cr\xE9er',
    'Create new orders and its associate components': 'Cr\xE9er de nouvelles commandes et de ses composants associ\xE9s',
    'List Orders': 'Liste des commandes',
    'View list of orders': 'Voir la liste des commandes',
    'Admin settings': 'Reglages admin',
    'Configure roles and privileges': 'Configurer les r\xF4les et les privileges',
    'Create new order':'Cr\xE9er nouvel ordre',
    'Configure workflow':'Configurer flux de travail',
    'List components':'Composants Liste'
};
navBtnSection_frenchLabelList = {
    'Print': 'Imprimer',
    'Save': 'Enregistrer',
    'Close': 'Fermer',
    'Cancel': 'Annuler',
    'Duplicate': 'Dupliquer',
    'Rewind': 'Rembobiner',
    'Forward to Next Stage': 'Transf\xE9rer \xE0 l\'\xE9tape suivante',
    'Order Id': 'Num\xE9ro de commande',
    'Requester Name': 'Nom emetteur',
    'Current Actor': 'Acteur actuel',
    'Stage': '\xC9tape',
    'Status': 'statut',
    'Total order amount': 'Montant total de la commande',
    'Refuse': 'Refuser',
    'Demote to previous step': 'Renvoyer au step pr\xE9c\XE9dent',
    'Demote to requester': 'Renvoyer au cr\xE9ateur'
};
navBtnSection_englishLabelList = {
    'Print': 'Print',
    'Save': 'Save',
    'Close': 'Close',
    'Cancel': 'Cancel',
    'Duplicate': 'Duplicate',
    'Rewind': 'Rewind',
    'Forward to Next Stage': 'Forward to Next Stage',
    'Order Id': 'Order Id',
    'Requester Name': 'Requester Name',
    'Current Actor': 'Current Actor',
    'Stage': 'Stage',
    'Status': 'Status',
    'Total order amount': 'Total order amount',
    'Refuse': 'Refuse',
    'Demote to previous step': 'Demote to previous step',
    'Demote to requester': 'Demote to requester'
};
orderDetails_frenchLabelList = {
    'Order Detail': 'D\xE9tails de la commande',
    'Site/Workshop Prototype': 'Site / Atelier Prototype',
    'Geosite': 'Geosite',
    'Prototype Order': 'Prototype Commander',
    'Proto Type': 'Type de Proto',
    'Type of the prototype order': 'Type de la commande prototype',
    'Date of the order': 'Date de la commande',
    'Total order amount': 'Montant total de la commande',
    'Order Status': 'Status de la commande',
    'PCC': 'PCC',
    'Open Order': 'Commande ouverte',
    'Frittage': 'Frittage',
    'E52': 'E52',
    'IntraLE': 'IntraLE',
    'Actor': 'Acteur',
    'Requester': 'Emetteur',
    'MEP Study': 'MEP Etude',
    'Quality': 'Qualit\xE9',
    'Proto workshop': 'Atelier Proto',
    'Control management': 'Contr\xF4le de Gestion',
    'FO Trade': 'Commerce FO',
    'ADV': 'ADV',
    'Project manager': 'Chef de Projet',
    'Customer Detail': 'D\xE9tail du client',
    'N0 customer order': 'de la commande client',
    'Customer name': 'Nom du client',
    'Customer code': 'Code client',
    'Branch code': 'Code branche',
    'Provider code': 'Code fournisseur',
    'Plateform': 'Plateforme',
    'Incoterms': 'Incoterms',
    'Place': 'Lieu',
    'Customer receiver name': 'Nom du receptionnaire client',
    'Customer receiver telephone': 'T\xE9l\xE9phone du receptionnaire client',
    'Allocation of turnover': 'Affectation du Chiffre d\'Affaire',
    'Final delivery Address': 'Address de livraiso finale',
    'Additional address': 'Compl\xE9ment d\'adresse',
    'Site address': 'Adresse du site',
    'Customer order': 'Commande client',
    'Add Attach': 'Ajouter Joindre',
    'Component': 'Composant',
    'Link': 'Link',
    'Customer ref': 'Cus ref',
    'Product Designation': 'P Designation',
    'Product Type': 'P Type',
    'USP': 'USP',
    'Total Quantity': 'T Qty',
    'Total amount': 'T amt',
    'Component status': 'Component status',
    'Quantity produced': 'Qty produced',
    'Quantity App. Quality': 'Qty App. Quality',
    'Quantity Dfi': 'Qty Dfi',
    'Quantity Delivered  to the customer': 'Qty Delivered',
    'Invoiced amount': 'Invoiced amt',
    'Draft': 'Brouillon',
    'Next': 'Prochain',
    'Back': 'Arri\xE9re',
    'Show': 'Montrer',
    'Entries': 'Entr\xE9es',
    'Back': 'Arri\xE9re',
    'Create component': 'Creation d\'un Comosant',
 	
};
orderDetails_englishLabelList = {
    'Order Detail': 'Order Detail',
    'Site/Workshop Prototype': 'Site / Workshop Prototype',
    'Geosite': 'Geosite',
    'Prototype Order': 'Prototype Order',
    'Proto Type': 'Proto Type',
    'Type of the prototype order': 'Type of the prototype order',
    'Date of the order': 'Date of the order',
    'Total order amount': 'Total Order Amount',
    'Order Status': 'Order Status',
    'PCC': 'PCC',
    'Open Order': 'Open Order',
    'Frittage': 'Frittage',
    'E52': 'E52',
    'IntraLE': 'IntraLE',
    'Actor': 'Actor',
    'Requester': 'Requester',
    'MEP Study': 'MEP Study',
    'Quality': 'Quality',
    'Proto workshop': 'Proto workshop',
    'Control management': 'Control management',
    'FO Trade': 'FO Trade',
    'ADV': 'ADV',
    'Project manager': 'Project manager',
    'Customer Detail': 'Customer Detail',
    'N0 customer order': 'Customer Order',
    'Customer name': 'Customer Name ',
    'Customer code': 'Customer Code',
    'Branch code': 'Branch Code',
    'Provider code': 'Provider Code',
    'Plateform': 'Plateform',
    'Incoterms': 'Incoterms',
    'Place': 'Place',
    'Customer receiver name': 'Customer Receiver Name',
    'Customer receiver telephone': 'Customer Receiver Telephone',
    'Allocation of turnover': 'Allocation of Turnover',
    'Final delivery Address': 'Final Delivery Address',
    'Additional address': 'Additional Address',
    'Site address': 'Site Address',
    'Customer order': 'Customer Order',
    'Add Attach': 'Add Attach',
    'Component': 'Component',
    'Link': 'Link',
    'Customer ref': 'Customer reference',
    'Product Designation': 'Product designation',
    'Product Type': 'Product Type',
    'USP': 'USP',
    'Total Quantity': 'Total Qty',
    'Total amount': 'Total amt',
    'Component status': 'Component status',
    'Quantity produced': 'Qty produced',
    'Quantity App. Quality': 'Qty App Quality',
    'Quantity Dfi': 'Qty DFi',
    'Quantity Delivered  to the customer': 'Qty Delivered',
    'Invoiced amount': 'Invoiced amt',
    'Draft': 'Draft',
    'Next': 'Next',
    'Show': 'Show',
    'Entries': 'Entries',
    'Back': 'Back',
    'Create component':'Create component',
    'Back': 'Back',
    'Next': 'Next'
};
componentCreation_frenchLabelList = {
	    'Order Details': 'D\xE9tails de la commande',
	    'Prototype Order': 'Prototype Commander',
	    'Order type': 'Type de commande',
	    'Customer order N0': 'N\xB0 de la commande client',
	    'Customer reference': 'R\xE9f\xE9rence client',
	    'Product type': 'Type de produit',
	    'Component ID': 'Identifiant du composant',
	    'Component status': 'Statut du composant',
	    'Component': 'Composant',
	    'Execution': 'Execution',
	    'Component description': 'Description du composant',
	    'Technical definition': 'D\xE9finition technique',
	    'Process validation': 'Validation process',
	    'Estimation Costs and Delays': 'Estimation Couts et delais',
	    'Qualities deliverables': 'D\xE9liverables qualit\xE9s',
	    'Customer reference': 'R\xE9f\xE9rence client',
	    'Unit selling price': 'Prix de vente unitaire',
	    'Customer': 'client',
	    'Direct delivery to the customer': 'Livraison direct au client',
	    'Product specification': 'D\xE9signation produit',
	    'Labo address or other': 'Adresse labo ou autre',
	    'Comment': 'Commentaire',
	    'Planning customer delivery': 'Planning livraison client',
	    'Quantity': 'Quantity',
	    'Date': 'Date',
	    'Edit': 'Edit',
	    'Delete': 'Delete',
	    'Total Quantity': 'Quantit\xE9 totale',
	    'Total amount': 'Montant total',
	    'Project manager': 'Chef de projet',
	    'R&D manager': 'Responsable R&D',
	    'Project phase': 'Phase projet',
	    'Valeo reference': 'R\xE9f\xE9rence Valeo',
	    'Technology': 'Technologie',
	    'WBS / OI code': 'Code WBS / OI',
	    'BE code': 'Code BE',
	    'MIP/PWA code': 'Code MIP/PWA',
	    'Validation process': 'Process validation',
	    'Plan of laboratory tests': 'Plan d\'essais de laboratoire',
	    'Process team member':'Membre de l\'\xE9quipe du processus',
	    'Nomenclature': 'Nomenclature',
	    'Plan': 'Plan',
	    'Add Attach': 'Ajouter Joindre',
	    'Test type': 'Tests Type',
	    'Test request N0': 'Test request N\xB0',
	    'ATP date delivery to Lab': 'ATP date delivery to Lab',
	    'Yes': 'Oui',
	    'No': 'Non',
	    'Process deliverable':'D\xE9livrables Process',
	    'YES (I specified process requirements)':'OUI (j\'ai sp\xE9cifi\xE9 les exigences Process)',
	    'Forecast planning of workshop':'Planification Pr\xE9visionnelle Atelier',
	    'Comments':'Comments',
	    'Reminder':'Pour rappel',
	    'Supported by':'Prise en charge par',
	    'List of prototypists':'Liste des Prototypistes',
	    'Component Projected Costs':'Co\xFBts Pr\xE9visionnels du composant',
	    'Estimated amount of workshop':'Quantit\xE9 pr\xE9visionnelle atelier',
	    'Estimated unit internal cost':'cou\xFBts interne pr\xE9visionnel unitaire',
	    'Estimated unit external cost':'co\xFBts externe pr\xE9visionnel unitaire',
	    'Estimated total cost components':'Co\xFBts pr\xE9visionnel total composants',
	    'Estimated time unit of components (hour)':'Temps pr\xE9visionnel unitaire comopsant (heure)',
	    'Hourly rate':'Taux horaire',
	    'Fixed costs':'Co\xFBts fixes',
	    'Estimated time total of components (hour)':'Temps pr\xE9visionnel total composants (heure)',
	    'Total cost':'Co\xFBt total',
	    'Quality deliverable':'D\xE9livrable Qualit\xE9',
	    'YES (I specified quality requirements)':'OUI (j\'ai sp\xE9cifi\xE9 les exigences qualit\xE9)',
	    'Parts production':'Production des pi\xE9ces',
	    'Quality approval':'Approbation Qualit\xE9',
	    'Validation test report(in case pf Testing Laboratory)':'Validation rapport d\'essai(en cas d\'essais Laboratoire)',
	    'Delivery/Billing':'Livraison/Facturation',
	    'Customer qty':'Qt\xE9 client',
	    'Qty lab test plan qty':'Qt\xE9 plan d\'essais de labo',
	    'Qty produced':'qt\xE9 produite',
	    'Qty test report':'Qt\xE9 rapport d\'essai',
	    'Qty approv. compliant quality':'Qt\xE9 approb Qualit\xE9 conforme',
	    'Qty approv. not compliant quality':'Qt\xE9 approb Qualit\xE9 non conforme',
	    'Delivered quantity':'Qt\xE9 livr\xE9e',
	    'Invoiced qty':'Qt\xE9 factur\xE9e',
	    'Creation':'Creation',
	    'Link':'Link',
	    'Made by':'Made by',
	    'MOD past hours':'MOD past hours',
	    'Notification':'Notification',
	    'Compliant':'Compliant',
	    'BLi#':'BLi#',
	    'Delivery':'Delivery',
	    'Approval':'Approval',
	    'Delivery date':'Delivery date',
	    'Qty delivered':'Qty delivered',
	    'N0 Marker':'N\xB0 Marker',
	    'BL Cordys':'BL Cordys',
	    'BL SAP':'BL SAP',
	    'Invoice N0':'Invoice N\xB0',
	    'Invoiced  qty':'Invoiced qty',
	    'Billing date':'Billing Date',
	    'Delivery notif.':'Delivery Notif.',
	    'Billing notif.':'Billing Notif.'
	};
	componentCreation_englishLabelList = {
	    'Order Details': 'Order Details',
	    'Prototype Order': 'Prototype Order',
	    'Order type': 'Order type',
	    'Customer order N0': 'Customer order N\xB0',
	    'Customer reference': 'Customer reference',
	    'Product type': 'Product type',
	    'Component ID': 'Component ID',
	    'Component status': 'Component status',
	    'Component': 'Component',
	    'Execution': 'Execution',
	    'Component description': 'Component description',
	    'Technical definition': 'Technical definition',
	    'Process validation': 'Process validation',
	    'Qualities deliverables': 'Qualities deliverables',
	    'Estimation Costs and Delays': 'Estimation Costs and Delays',
	    'Customer reference': 'Customer reference',
	    'Unit selling price': 'Unit selling price',
	    'Customer': 'Customer',
	    'Direct delivery to the customer': 'Direct delivery to the customer',
	    'Product specification': 'Product specification',
	    'Labo address or other': 'Labo address or other',
	    'Comment': 'Comment',
	    'Planning customer delivery': 'Planning customer delivery',
	    'Quantity': 'Quantity',
	    'Date': 'Date',
	    'Edit': 'Edit',
	    'Delete': 'Delete',
	    'Total Quantity': 'Total Quantity',
	    'Total amount': 'Total amount',
	    'Project manager': 'Project manager',
	    'R&D manager': 'R&D manager',
	    'Project phase': 'Project phase',
	    'Valeo reference': 'Valeo reference',
	    'Technology': 'Technology',
	    'WBS / OI code': 'WBS / OI code',
	    'BE code': 'BE code',
	    'MIP/PWA code': 'MIP/PWA code',
	    'Validation process': 'Validation process',
	    'Plan of laboratory tests': 'Plan of laboratory tests',
	    'Process Team Member':'Process Team Member',
	    'Nomenclature': 'Nomenclature',
	    'Plan': 'Plan',
	    'Add Attach':'Add Attach',
	    'Test type': 'Tests Type',
	    'Test request N0': 'Test request N\xB0',
	    'ATP date delivery to Lab': 'ATP date delivery to Lab',
	    'Yes': 'Yes',
	    'No': 'No',
	    'Process deliverable':'Process deliverable',
	    'YES (I specified process requirements)':'YES (I specified process requirements)',
	    'Forecast planning of workshop':'Forecast planning of workshop',
	    'Comments':'Comments',
	    'Reminder':'Reminder',
	    'Supported by':'Supported by',
	    'List of prototypists':'List of prototypists',
	    'Component Projected Costs':'Component Projected Costs',
	    'Estimated amount of workshop':'Estimated amount of workshop',
	    'Estimated unit internal cost':'Estimated unit internal cost',
	    'Estimated unit external cost':'Estimated unit external cost',
	    'Estimated total cost components':'Estimated total cost components',
	    'Estimated time unit of components (hour)':'Estimated time unit of components (hour)',
	    'Hourly rate':'Hourly rate',
	    'Fixed costs':'Fixed costs',
	    'Estimated time total of components (hour)':'Estimated time total of components (hour)',
	    'Total cost':'Total cost',
	    'Quality deliverable':'Quality deliverable',
	    'YES (I specified quality requirements)': 'YES (I specified quality requirements)',
	    'Parts production':'Parts production',
	    'Quality approval':'Quality approval',
	    'Validation test report(in case pf Testing Laboratory)':'Validation test report(in case pf Testing Laboratory)',
	    'Delivery/Billing':'Delivery/Billing',
	    'Customer qty':'Customer qty',
	    'Qty lab test plan qty':'Qty lab test plan qty',
	    'Qty produced':'Qty produced',
	    'Qty test report':'Qty test report',
	    'Qty approv. compliant quality':'Qty approv. compliant quality',
	    'Qty approv. not compliant quality':'Qty approv. not compliant quality',
	    'Delivered quantity':'Delivered quantity',
	    'Invoiced qty':'Invoiced qty',
	    'Creation':'Creation',
	    'Link':'Link',
	    'Made by':'Made by',
	    'MOD past hours':'MOD past hours',
	    'Notification':'Notification',
	    'Compliant':'Compliant',
	    'BLi#':'BLi#',
	    'Delivery':'Delivery',
	    'Approval':'Approval',
	    'Delivery date':'Delivery date',
	    'Qty delivered':'Qty delivered',
	    'N0 Marker':'N\xB0 Marker',
	    'BL Cordys':'BL Cordys',
	    'BL SAP':'BL SAP',
	    'Invoice N0':'Invoice N\xB0',
	    'Invoiced  qty':'Invoiced  qty',
	    'Billing date':'Billing date',
	    'Delivery notif.':'Delivery notif.',
	    'Billing notif.':'Billing notif.'

	};
adminSetting_frenchLabelList = {
		'Application Configuration':'Configuration de l\'application',
		'List of Actors':'Liste des Acteurs',
		'List of Incoterms':'Liste des Incoterms',
		'List of Clients':'Liste des clients',
		'List of Prototypists':'Liste des prototypistes',
		'List of Plateforms':'Liste des Plateformes',
		'List of Products Types':'Liste des Produits Types',
		'List of Technologies':'Liste des Technologies',
		'List of R & D Leaders':'Liste des R & D Leaders',
		'List of Clients and Lab Addresses':'Liste des clients et des adresses de laboratoire',
		'List of Locations':'Liste des emplacements',
		'List of Sites':'Liste des sites',
		'Workflow Configuration':'Configuration de workflow',
		'Administrator View':'Administrator Voir',
		'Delete draft requests':'Supprimer les projets de demandes',
		'Restart process':'processus de red\xE9marrage',
		'Define a delegate for a period of time':'D\xE9finir un d\xE9l\xE9gu\xE9 pour une p\xE9riode de temps',
		'App Configuration':'Configuration App',
		'Data':'Donn\xE9es',
	    'MEP Study': 'MEP Etude',
	    'Quality': 'Qualit\xE9',
	    'Proto workshop': 'Atelier Proto',
	    'Management Control': 'Contr\xF4le de Gestion',
	    'FO Trade': 'Commerce FO',
		'ADV':'ADV',
	    'Project manager': 'Chef de Projet',
		'Site':'Site',
	    'Edit': 'Modifier',
	    'Delete': 'Effacer'
};
adminSetting_englishLabelList = {
		'Application Configuration':'Application Configuration',
		'List of Actors':'List of Actors',
		'List of Incoterms':'List of Incoterms',
		'List of Clients':'List of Clients',
		'List of Prototypists':'List of Prototypists',
		'List of Plateforms':'List of Platforms',
		'List of Products Types':'List of Products Types',
		'List of Technologies':'List of Technologies',
		'List of R & D Leaders':'List of R & D Leaders',
		'List of Clients and Lab Addresses':'List of Clients and Labo Addresses',
		'List of Locations':'List of Locations',
		'List of Sites':'List of Sites',
		'Workflow Configuration':'Workflow Configuration',
		'Administrator View':'Administrator View',
		'Delete draft requests':'Delete draft requests',
		'Restart process':'Restart process',
		'Define a delegate for a period of time':'Define a delegate for a period of time',
		'App Configuration':'App Configuration',
		'Data':'Data',
		'MEP Study':'MEP Study',
		'Quality':'Quality',
		'Proto workshop':'Proto workshop',
		'Management Control':'Management Control',
		'FO Trade':'FO Trade',
		'ADV':'ADV',
		'Project manager':'Project manager',
		'Site':'Site',
		'Delete':'Delete'
};

 /*============================== Order Creation (in what stage it is) =========================*/

